// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhkbegzqfhgxbaqysfot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5oa2JlZ3pxZmhneGJhcXlzZm90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NDE5MTYsImV4cCI6MjA2MTUxNzkxNn0.Mgi5q2eynXMnk1Ez9BrXFHe6uAPdeHHuVrMJ8asULwc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);